config/routes.rb
Hassler::Application.routes.draw do

  root 'static_pages#home'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/acknowledgements', to: 'static_pages#acknowledgements', via: 'get'

  match '/projects',to: 'projects#index', via: 'get'
  match '/projects/:project',to:'projects#show', via: 'get'

  

  resources :posts

  get '/connectfour' => redirect("/projects/connectfour")
  get '/hacc' => redirect("/projects/hacc")
  get '/automata' => redirect("/projects/automata")
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 5 }
    validates :text, presence: true

    def full_url
		return url if url.start_with? 'http'
		return "posts/#{url}"
	end

	def to_param
		"#{url}"
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, uniqueness: true

	def full_url
		return url if url.start_with? 'http'
		return "projects/#{url}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :authenticate, except: [:show, :index]

	def authenticate
		if Rails.env == 'development'
			return true
		end
		authenticate_or_request_with_http_basic do |username, pass|
			username == ENV['hassler_blog_username'] and pass == ENV['hassler_blog_pass']
		end
	end

	# create a new post
	def new
		@post = Post.new
	end
	def create
		@post = Post.new(params[:post].permit(:title, :text, :caption, :url, :imgcaption, :file))
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end
	def show
		@post = Post.find_by_url(params[:id])
		# @post = Post.find(params[:id])
	end

	# edit posts
	def edit
		@post = Post.find_by_url(params[:id])
		# @post = Post.find(params[:id])
	end
	def update
		@post = Post.find_by_url(params[:id])
		# @post = Post.find(params[:id])
		
		# from http://stackoverflow.com/questions/17713570/undefined-method-permit-for-nilnilclass-in-rails-guide-section-5-7
		if params.has_key?(:post)
			@post.update(params[:post].permit(:title, :text, :caption, :url, :imgcaption, :file))
			redirect_to @post
		else
			render 'edit'
		end
	end

	# delete posts
	def destroy
		@post = Post.find_by_url(params[:id])
		# @post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	# index
	def index
		@posts = Post.all
	end

	private
	def post_params
		params.require(:post).permit(:title, :text, :caption, :url, :imgcaption, :file)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@project = Project.new
	end
	def index
		@projects = Project.all
	end

	def show
		@project = Project.find_by!(url: params[:project])
		render template: 'projects/' + @project.url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about	
  end

  def contact
  end

  def acknowledgements
  end

  def projects
  end

  def cv
  end

  def resume
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  # from http://ruby.railstutorial.org/chapters/rails-flavored-ruby#top
  def full_title(page_title)
    base_title = "Hassler Thurston"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}".html_safe
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="row-fluid footer">
  <small>
    J. Hassler Thurston, University of Rochester Class of 2017
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acknowledgements",   acknowledgements_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="height: 40px" role="navigation">
		<div class="navbar-inner">
			<ul class="nav navbar-nav">
				<li><%= link_to "Home",    root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Projects",   projects_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
				<li><%= link_to "Blog",   posts_path %></li>
				<li><%= link_to "Resume", '/Thurston_resume.pdf' %></li>
			</ul>
		</div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<div class="container">
		<%= yield %>
	</div>
	<div class="container">
		<%= render 'layouts/footer' %>
	</div>

</body>
</html>

app/views/layouts/projects.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= yield :head %>

  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<div class="container">
		<%= yield %>
	</div>
	<div class="container">
		<%= render 'layouts/footer' %>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => 50 %>
  </p>

  <p>
    <%= f.label :caption %><br>
    <%= f.text_area :caption, :cols => 50, :rows => 3 %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url, :size => 50 %>
  </p>

  <p>
    <%= f.label :file %> (Picture)<br>
    <%= f.text_field :file, :size => 50 %>
  </p>

  <p>
    <%= f.label :imgcaption %><br>
    <%= f.text_field :imgcaption, :size => 50 %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, :cols => 50, :rows => 10 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form" %>

<%= button_to "delete", '/posts/'+@post.url, :method=>:delete, :class=>:destroy, :confirm => "Are you sure you want to delete this post?" %>

<br>

<%= link_to 'Back', @post %>

app/views/posts/index.html.erb
<% provide(:title, 'Blog') %>

	<h1>Blog</h1>
	<br>
    	<div class="container-fluid">
			<% @posts.each do |post| %>
				<div class="row">
					<div class="col-md-3 col-md-offset-3">
						<p><%= image_tag post.file, height:"150", width:"200" %></p>
					</div>
					<div class="col-md-4">
						<h3><%= link_to post.title, post_path(post) %></h3><br>
						<%= post.caption %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-5 col-md-offset-4">
						<hr>
					</div>
				</div>
			<% end %>
		</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row-fluid">
	<div class="col-md-6 col-md-offset-3">

		<%= render "form" %>

		<%= link_to 'Back', posts_path %>
	</div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<% content_for :head do %>
	<%= stylesheet_link_tag "blog", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "blog", "data-turbolinks-track" => true %>
<% end %>





<h1><%= @post.title %></h1>
<div class="row-fluid">
	<div class="col-md-6 col-md-offset-3">
		<%= image_tag @post.file, height:"300", width:"400" %>
		<h6><%= @post.imgcaption %></h6>

		<p>
		  <b><%= simple_format @post.caption %></b>
		</p>
		 
		<p>
		  <%= simple_format @post.text %>
		</p>
		<hr>
		<%= link_to "Back", posts_path %>
	</div>
</div>

app/views/projects/connectfour.html.erb
<% provide(:title, 'Connect Four') %>
<% content_for :head do %>
	<%= stylesheet_link_tag "connectfour", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "game", "data-turbolinks-track" => true %>
<% end %>

	<h1>Connect Four</h1>
	<h2>
        <iframe width="420" height="315" src="//www.youtube.com/embed/RrTD9L3gqYc?rel=0" frameborder="0" allowfullscreen>
        </iframe>
    </h2>
	<div class="row-fluid">
    	<div class="col-md-4 col-md-offset-4">
    		<section id="game_start" class="form-horizontal">
    		  <div class="form-group">
    		    <label class="col-sm-2 control-label" for="newgame_columns">Columns</label>
    		    <div class="col-sm-10">
    		      <input type="number" class="form-control" id="newgame_columns" placeholder="7">
    		    </div>
    		  </div>
    		  <div class="form-group">
    		    <label class="col-sm-2 control-label" for="newgame_rows">Rows</label>
    		    <div class="col-sm-10">
    		      <input type="number" class="form-control" id="newgame_rows" placeholder="6">
    		    </div>
    		  </div>
    		  <div class="form-group">
    		    <label class="col-sm-2 control-label">Turn</label>
    		    <div class="col-sm-10">
    		      <div class="row">
    		        <div class="col-sm-6">
    		          <label class="radio-inline">
    		            <input type="radio" name="newgame_turn" value="0">First
    		          </label>
    		        </div>
    		        <div class="col-sm-6">
    		          <label class="radio-inline">
    		            <input type="radio" name="newgame_turn" value="1">Second
    		          </label>
    		        </div>
    		      </div>
    		    </div>
    		  </div>
    		</section>
			<input type="hidden" id="newgame_moves" value="[]">
    		<section id="game">
    		</section>
		    <div class="form-group" id="newgame_div">
		      <div class="col-md-6 col-md-offset-3">
		        <button id="newgame_button" class="btn btn-primary btn-block">New game</button>
		      </div>
		    </div>
		    <!-- what a hack -->
		    <br>
		    <div class="form-group" id="restartgame_div" style="display: none">
		      <div class="col-md-6 col-md-offset-3">
		        <button id="restart_button" class="btn btn-primary btn-block">Start new game</button>
		      </div>
		    </div>
    	</div>
    	<div class="col-md-6 col-md-offset-3">
    		<hr>
    		<p style="text-align: center">To access the source code, check out the project's <a href="http://github.com/jthurst3/connectfour">GitHub</a> site.</p>
    	</div>
    </div>
    <%= javascript_include_tag "connectfour", "data-turbolinks-track" => true %>

app/views/projects/connectfour_gameboard.html.erb
<input type="hidden" id="newgame_moves" value="[]">
<!-- inspired by http://www.youtube.com/watch?v=qaGd65opzgo -->
<div id="game_board">
	
</div>

app/views/projects/cribbage.html.erb
<% provide(:title, 'Cribbage') %>
<% content_for :head do %>
	<%= stylesheet_link_tag "connectfour", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "game", "data-turbolinks-track" => true %>
<% end %>

	<h1>Connect Four</h1>
	<h2>
        <iframe width="420" height="315" src="//www.youtube.com/embed/RrTD9L3gqYc?rel=0" frameborder="0" allowfullscreen>
        </iframe>
    </h2>
	<div class="row-fluid">
    	<div class="col-md-8 col-md-offset-2">
    		<section id="game">
    			<input type="hidden" id="newgame_moves" value="[]">
    			Columns: <input id="newgame_columns" placeholder="7"><br>
    			Rows: <input id="newgame_rows" placeholder="6"><br>
    			Turn: <input type="radio" name="newgame_turn" value="1">First &nbsp;
    			<input type="radio" name="newgame_turn" value="2">Second<br>
    			<button id="newgame_button" class="btn btn-primary">New game</button>
    		</section>
    		<hr>
    		<p style="text-align: center">To access the source code, check out the project's <a href="http://github.com/jthurst3/connectfour">GitHub</a> site.</p>
    	</div>
    </div>
    <script type="text/javascript">
    $(document).on('click', "#newgame_button", function() {
    	return validate_create();
    });
    $(document).on('click', "#restart_button", function() {
    	start_game();
    });
    // initializes the game board
    function create_game(columns, rows, turn) {
    	// inspired by http://www.youtube.com/watch?v=qaGd65opzgo
    	// and (modified from) http://jsfiddle.net/pendensproditor/9zA6g/

    	// initialize string of HTML to replace
    	var board_string = "";
		var board_header = "<table id=\"game_board\">\n";
		var board_footer = "</table>\n";
		var header_header = "<thead>";
		var header_footer = "</thead>";
		var body_header = "<tbody>";
		var body_footer = "</tbody>";
		var row_header = "<tr>";
		var row_footer = "</tr>";
		var restart_html = "<button id=\"restart_button\" class=\"btn btn-primary\">Start new game</button>";
		// table headers
		var header_element = function(column) {
			return "<th data-col=\"" + column + "\" class=\"table_header\" id=\"" + column + "\">&darr;</th>";
		}
		// elements
		var table_element = function(column, row) {
			return "<td id=\"" + column + "-" + row + "\"></td>\n";
		}
		// set up table header
		board_string += (board_header + header_header + row_header);
		for(var i = 0; i < columns; i++) {
			board_string += header_element(i);
		}
		// set up table body
		board_string += (row_footer + header_footer + body_header);
		for(var i = 0; i < rows; i++) {
			var row = "";
			row += row_header;
			for(var j = 0; j < columns; j++) {
				row += table_element(j, rows-i-1);
			}
			row += row_footer;
			board_string += row;
		}
		board_string += board_footer;
		board_string += restart_html;
		var txt = $("section#game").html(board_string);

		// initialize the global variables
		initializeVars(columns, rows);

		// if the computer goes first, get its move
		if(computer_player == 1) {
			send_move();
		}
	};

	// relevant global variables
	var columns, rows, moves, board, human_player, game_turn, computer_player;

	// initializes global variables relevant to the Connect Four game
	var initializeVars = function(col, row) {
		columns = col;
		rows = row;
		moves = [];
		board = [];
		for(var i = 0; i < col; i++) {
			board.push([]);
		}
		human_player = turn;
		computer_player = (turn%2)+1;
		game_turn = 1;
	}

	// makes a move
	$(document).on('click', "th.table_header", function() {
		var column_number = parseInt($(this).attr("id"));
		var legal = isLegal(column_number);
		if(legal) {
			board[column_number].push(human_player);
			moves.push(column_number);
			update_board(column_number);
			update_turn();
			send_move();
		}
	});

	// updates the layout of the board given a legal move
	var update_board = function(column_number) {
		// get the ID of the cell we're updating
		var coords = get_lastmove_id(column_number);
		// paint that cell
		paint(coords, game_turn);
	}
	// gets the ID of the cell to update
	var get_lastmove_id = function(column_number) {
		// get the row
		var row = board[column_number].length - 1;
		// construct the string ID
		var strID = String(column_number) + "-" + String(row);
		// return it
		return strID;
	}
	// paints the relevant cell
	var paint = function(strID, player) {
		if(player == human_player)
			$("td#" + strID).addClass("humanplayer");
		else
			$("td#" + strID).addClass("computerplayer");
	}
	// updates the player whose turn it is
	var update_turn = function() {
		if(game_turn == 1)
			game_turn = 2;
		else game_turn = 1;
	}

	// sends the last move to the Connect Four server; retrieves the computer's move
	var send_move = function() {
		// from http://stackoverflow.com/questions/247483/http-get-request-in-javascript
		// and http://stackoverflow.com/questions/6055714/how-to-send-json-object-or-string-data-from-javascript-xmlhttprequest-to-mvc-c
		var data = {
			'columns': parseInt(columns),
			'rows': parseInt(rows),
			'moves': moves
		};
		var xmlHTTP = new XMLHttpRequest();
		xmlHTTP.open("POST", "http://hassler-connectfour.herokuapp.com/move", false);
		xmlHTTP.setRequestHeader('Content-Type', 'application/json');
		xmlHTTP.send(JSON.stringify(data));

		// receive the request and decode it
		var response = xmlHTTP.responseText;
		// from http://stackoverflow.com/questions/9036429/convert-object-string-to-json
		var json = eval('(' + response + ')');
		if(json['moves'] == undefined) {
			alert("There was an error processing your request.");
			start_game();
		} else if(json['winner'] != 0 && json['winner'] != computer_player && json['winner'] != -1) {
			// print out a winning message and restart the game
			var winning_message = get_winning_message(json['winner']);
			alert(winning_message);
			start_game();
		} else {
			var col_num = json['moves'][json['moves'].length-1];
			board[col_num].push(computer_player);
			moves.push(col_num);
			update_board(col_num);
			if(json['winner'] == computer_player || json['winner'] == -1) {
				// print out a winning message and restart the game
				var winning_message = get_winning_message(json['winner']);
				alert(winning_message);
				start_game();
			}
			update_turn();
		}
	}

	// checks to see if a move is legal, given the state of the board
	var isLegal = function(column_number) {
		// make sure the column number is valid
		if(column_number < 0 || column_number >= columns) {
			return false;
		}
		// then check to see if that column is filled up
		return board[column_number].length < rows;
	}
	// returns a string if somebody has won the game
	var get_winning_message = function(player) {
		if(player == -1)
			return "Game is a draw. Can you do better?";
		else if(player == 0)
			return "Game is not over.";
		else if(player == human_player)
			return "You have just beaten my computer program! Congratulations!";
		else if(player == computer_player)
			return "You just lost to my computer program. You can do better than that.";
		else return "There was an error processing your request.";
	}

	// sets up the board for a new game
	var start_game = function() {
		// taken from the top of the page
		var html_string = "<input type=\"hidden\" id=\"newgame_moves\" value=\"[]\">Columns: <input id=\"newgame_columns\" placeholder=\"7\"><br>Rows: <input id=\"newgame_rows\" placeholder=\"6\"><br>Turn: <input type=\"radio\" name=\"newgame_turn\" value=\"1\">First &nbsp;<input type=\"radio\" name=\"newgame_turn\" value=\"2\">Second<br><button id=\"newgame_button\" class=\"btn btn-primary\">New game</button>";
    	$("section#game").html(html_string);
	}
    </script>

app/views/projects/elections.html.erb
<% provide(:title, 'Elections') %>
<% content_for :head do %>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<%= javascript_include_tag "elections/javascripts/main.js", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "elections/javascripts/template.js", "data-turbolinks-track" => true %>
<% end %>

	<h1 id="title"></h1>
	<p id="subtitle"></p>
	<div class="wrapper">
      <nav>
        <ul></ul>
      </nav>
      <section>
        <h3 id="text">
        </h3>
      </section>
    </div>
	<div class="row-fluid">
    	<div class="col-md-8 col-md-offset-2">
    		
    		<hr>
    		<p style="text-align: center">To access the source code, check out the project's <a href="http://github.com/jthurst3/elections">GitHub</a> site.</p>
    	</div>
    </div>

app/views/projects/index.html.erb
<% provide(:title, 'Projects') %>

    <h1>Projects</h1>
    <br>
    	<div class="container-fluid">
			<% @projects.each do |project| %>
				<div class="row">
					<div class="col-md-3 col-md-offset-3">
						<p><%= image_tag project.file, height:"150", width:"200" %></p>
					</div>
					<div class="col-md-4">
						<h3><%= link_to project.name, project.full_url %></h3><br>
						<%= project.description %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-5 col-md-offset-4">
						<hr>
					</div>
				</div>
			<% end %>
		</div>

app/views/static_pages/acknowledgements.html.erb
<% provide(:title, 'Acknowledgements') %>

    <h1>Acknowledgements</h1>
    <div class="row-fluid">
    	<div class="col-md-6 col-md-offset-3">
    		<section id="credits">
				  <h3>Credits</h3>
				  <hr>
				  <p>
					  <ul>
					  	<li><a href="http://ruby.railstutorial.org/ruby-on-rails-tutorial-book">Ruby on Rails Tutorial</a> by Michael Hartl</li>
					  	<li>Homepage image credit: <a href="http://www.rochesterphotographers.com/">Rochester Photography</a></li>
					  	<li>Project image credits:
					  		<ul>
						  		<li>Unsolved Problems Database: <a href="http://pixabay.com/en/puzzle-complete-part-share-fit-63626/">Pixabay</a></li>
						  		<li>Connect Four: <a href="http://commons.wikimedia.org/wiki/File:Puissance4_01.svg">Wikimedia Commons, By User François Haffner on fr.wikipedia [Public domain]</a></li>
						  		<li>Human-Aided Computer Composition: Sally Thurston (Creative Ability Development Tour Group performing one of the computer's compositions in Providence, RI, April 2011)</li>
						  		<li>Automata Game: Own work (created in Wolfram Mathematica 9)</li>
						  	</ul>
					  	</li>
					  	<li>Project add-ons:
					  		<ul>
					  			<li>Human-Aided Computer Composition: <a href="http://mudcu.be/midi-js/">MIDI.js</a></li>
					  		</ul>
					  	</li>
					  </ul>
				  </p>
			  </section>
			  <section id="stack">
				  <h3>Technology Stack</h3>
				  <hr>
				  <p>
					  <ul>
					  	<li>Heroku (web hosting)</li>
					  	<li>GitHub (project hosting)</li>
					  	<li>DNSimple (domain name management)</li>
					  	<li>Ruby on Rails (web development framework)</li>
					  	<li>Bootstrap (CSS and styling)</li>
					  </ul>
				  </p>
			  </section>
    	</div>
    </div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

    <h1>Contact</h1>
    <div class="row-fluid">
    	<div class="col-md-4 col-md-offset-4 center">
	    	<p>
				<a href="mailto:jthurst3@u.rochester.edu"><i class="fa fa-3x fa-envelope-o" style="color: red"></i></a>
				<a href="http://www.linkedin.com/pub/hassler-thurston/76/12a/209"><i class="fa fa-3x fa-linkedin-square" style="color: light blue"></i></a>
				<a href="https://github.com/jthurst3"><i class="fa fa-3x fa-github" style="color: black"></i></a>
				<a href="https://twitter.com/HasslerThurston"><i class="fa fa-3x fa-twitter" style="color: light blue"></i></a>
		    </p>
    	</div>
    </div>
    <br><br><br>
    <div class="row-fluid">
	    <div class="col-md-2 col-md-offset-5 center">
	    	<p>
	    		J. Hassler Thurston<br>
	    		34 Wild Berry Lane<br>
	    		Pittsford, NY 14534<br>
	    	</p>
	    </div>
	</div>

app/views/static_pages/cv.html.erb
<% provide(:title, 'CV') %>

    <h1>CV</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>

app/views/static_pages/home.html.erb
    <h1>J. Hassler Thurston</h1>
	<!-- <div class="row-fluid">
    	<div class="col-md-4 col-md-offset-4"> -->
    		<center><%= image_tag "web_photo.jpg" , height:"430", width:"400" %></center>
		    <p style="text-align: center">
		      University of Rochester Class of 2017<br>
		      Computer Science
		    </p>
    	<!-- </div>
    </div> -->

app/views/static_pages/resume.html.erb
<% provide(:title, 'Resume') %>

    <h1>Resume</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>